//----------------------------------------------------------------------------------------------------------------------
// Expression evaluator
//----------------------------------------------------------------------------------------------------------------------

#pragma once

#include <config.h>
#include <types.h>
#include <emulator/spectrum.h>

#include <map>
#ifdef __APPLE__
#   include <experimental/optional>
#else
#   include <optional>
#endif
#include <variant>

//----------------------------------------------------------------------------------------------------------------------
// ExprValue
// Stores an expression's value and type
//----------------------------------------------------------------------------------------------------------------------

class ExprValue
{
public:
    ExprValue();
    explicit ExprValue(i64 value);
    explicit ExprValue(MemAddr value);

    ExprValue(const ExprValue& other);
    ExprValue& operator= (const ExprValue& other);

    enum class Type
    {
        Invalid,
        Integer,
        Address,
    };

    Type getType() const { return m_type; }
    operator i64() const { return get<i64>(m_value); }
    operator MemAddr() const { return get<MemAddr>(m_value); }

    //
    // Operations
    //

    ExprValue operator+ (const ExprValue& other) const;
    ExprValue operator- (const ExprValue& other) const;
    ExprValue operator* (const ExprValue& other) const;
    ExprValue operator/ (const ExprValue& other) const;
    ExprValue operator% (const ExprValue& other) const;
    ExprValue operator| (const ExprValue& other) const;
    ExprValue operator& (const ExprValue& other) const;
    ExprValue operator^ (const ExprValue& other) const;
    ExprValue operator<< (const ExprValue& other) const;
    ExprValue operator>> (const ExprValue& other) const;

    //
    // Convenience casts
    //
    u8 r8() const { assert(m_type == Type::Integer); return u8(get<i64>(m_value)); }
    u16 r16() const { assert(m_type == Type::Integer); return u16(get<i64>(m_value)); }

private:
    Type m_type;
    variant<i64, MemAddr> m_value;
};

//----------------------------------------------------------------------------------------------------------------------
// Represents an expression (calculated or not calculated)
//----------------------------------------------------------------------------------------------------------------------

class Expression
{
public:
    Expression();

    enum class ValueType
    {
        UnaryOp,
        BinaryOp,
        OpenParen,
        CloseParen,
        Integer,
        Symbol,
        Char,
        Dollar,
    };

    struct Value
    {
        ValueType               type;
        i64                     value;
        const Lex::Element*     elem;       // The element that described the operand

        Value(ValueType type, i64 value, const Lex::Element* e) : type(type), value(value), elem(e) {}
    };

    void addValue(ValueType type, i64 value, const Lex::Element* e);
    void addUnaryOp(Lex::Element::Type op, const Lex::Element* e);
    void addBinaryOp(Lex::Element::Type op, const Lex::Element* e);
    void addOpen(const Lex::Element* e);
    void addClose(const Lex::Element* e);
    void set(i64 result) { m_result = ExprValue(result); }

    bool eval(Assembler& assembler, Lex& lex, MemAddr currentAddress);

    ExprValue result() const { return m_result; }
    u8 r8() const { NX_ASSERT(m_result.getType() == ExprValue::Type::Integer); return m_result.r8(); }
    u16 r16() const { NX_ASSERT(m_result.getType() == ExprValue::Type::Integer); return m_result.r16(); }

    // Converts an address or integer into a 16-bit integer (if within Z80 view)
    u16 make16(Assembler& assembler, Lex& lex, const Lex::Element& e, const Spectrum& speccy);

private:
    vector<Value>   m_queue;
    ExprValue       m_result;
};


//----------------------------------------------------------------------------------------------------------------------
// Expression evaluator
//----------------------------------------------------------------------------------------------------------------------

class ExpressionEvaluator
{
public:
    ExpressionEvaluator();

    optional<ExprValue> parseExpression(const vector<u8>& text);
    optional<ExprValue> parseExpression(Lex& lex, const Lex::Element*& e);

private:
    StringTable             m_symbols;      // Symbols generated by the lexical analysis
    map<i64, ExprValue>     m_values;
};
